apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
  labels:
    id: c0904322       # replace with your actual college ID
    app: nginx
    env: dev
spec:
  selector:
    id: c0904322
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
